import js from '@eslint/js'
import tseslint from 'typescript-eslint'


import svelte from 'eslint-plugin-svelte'

export default tseslint.config(
  // `.astro/` is generated by `astro sync` on every dev/build: linting it reports
  // problems in code nobody wrote and nobody can fix.
  { ignores: ['dist', 'node_modules', '.astro'] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { varsIgnorePattern: '^_', argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
  // A .svelte file is markup, script and style in one, and only svelte-eslint-parser
  // can read it. The recommended set is kept whole: most of what it reports is the
  // compiler's own class of mistake (a missing key, a store read without `$`, an
  // unused CSS selector) rather than style.
  ...svelte.configs.recommended,
  {
    files: ['**/*.svelte', '**/*.svelte.ts'],
    // The typescript-eslint rules below come from its preset above, which does
    // not apply to .svelte; the plugin has to be named again here or ESLint
    // refuses the whole config rather than the two rules.
    plugins: { '@typescript-eslint': tseslint.plugin },
    languageOptions: {
      // The parser above reads the file; this one reads the <script lang="ts">
      // inside it. Without it every type annotation is a syntax error.
      parserOptions: { parser: tseslint.parser },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { varsIgnorePattern: '^_', argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
)
