// Code generated by server/cmd/protocolgen. DO NOT EDIT.
//
// Source: server/protocol. Regenerate with "make protocol"; CI fails the build if
// this file and the Go source have drifted apart, so editing it by hand is
// undone by the next run rather than merged.
//
// This file carries the protocol's TypeScript types.

// CardColor is a card colour, or the table's active colour, as it travels.
// ColorWild is what a wild card carries before its owner names a real one; it
// must never reach a game state's active colour.
export type CardColor =
  | 'red'
  | 'yellow'
  | 'green'
  | 'blue'
  | 'wild'

// CardKind is a card's kind as it travels. KindWild is the plain wild card;
// KindGlobalSwitch is LOCO's own, a wild that rotates every hand.
export type CardKind =
  | 'number'
  | 'skip'
  | 'reverse'
  | 'draw_two'
  | 'wild'
  | 'wild_draw_four'
  | 'swap'
  | 'global_switch'

// MatchFormat is the best-of-N format a table is playing.
export type MatchFormat =
  | 'BO1'
  | 'BO3'
  | 'BO5'
  | 'BO7'

// ClientMsgType enumerates message types sent from client to server.
export type ClientMsgType =
  // Lobby
  | 'create_room'
  | 'join_room'
  | 'start_game'
  | 'add_bot'
  | 'set_match_format'
  | 'set_max_players'
  // CMsgKickPlayer frees a seat at the host's table, named by TargetIndex. The
  // only lobby control that acts on somebody else, and the only way to take a
  // bot's seat back. Lobby only: once the cards are out a seat belongs to a
  // match, not to the roster.
  | 'kick_player'
  // CMsgTransferHost hands the table to the seat named by TargetIndex. The host
  // is seat 0 and nothing else, so this is a seat swap and every host control
  // answers to the other player from the acknowledgement onwards. Lobby only,
  // never to a bot: a table nobody can start is the one thing this must not be
  // able to produce.
  | 'transfer_host'
  // CMsgRematch returns a finished room to the lobby with the same players.
  | 'rematch'
  // Matchmaking: a 1v1 against whoever is looking for the same thing. The
  // queue is anonymous and its size is never on the wire. See
  // SMsgMatchmakingQueued.
  | 'find_match'
  | 'cancel_matchmaking'
  // CMsgLeaveRoom gives up the seat this socket holds without dropping the
  // connection. It is what "search for another opponent" is built on, and in a
  // matchmade match in progress it is a deliberate forfeit.
  | 'leave_room'
  // Gameplay
  | 'play_card'
  | 'draw_card'
  | 'pass_turn'
  | 'declare_uno'
  | 'catch_uno'
  | 'counter_draw'
  // CMsgMapReady tells the server this client has the match's map decoded and
  // is ready to play. Sent once per match, in answer to SMsgMatchLoading.
  | 'map_ready'
  // CMsgInterruptPlay is the realtime "lead-taking" / jump-in message.
  // Body may carry either a singular Card OR a PlayCards array (batch identical-card
  // interrupt). interrupt_play_card is accepted as an alias for the same handler.
  | 'interrupt_play'
  | 'interrupt_play_card'
  // Dev / E2E only (requires LOCO_E2E=1 env var on the server)
  | 'debug_set_state'

// ServerMsgType enumerates message types sent from server to client.
export type ServerMsgType =
  // Lobby
  | 'room_created'
  | 'room_joined'
  | 'player_joined'
  | 'player_left'
  | 'player_disconnected'
  | 'player_reconnected'
  | 'lobby_config_changed'
  | 'game_started'
  // SMsgMatchmakingQueued acknowledges a find_match. It carries no queue size,
  // no position and no estimate, on purpose: how many people are looking for a
  // game is nobody's business but the operator's, and a number that reads "1"
  // tells a player to give up. The client times its own wait instead.
  | 'matchmaking_queued'
  // SMsgMatchmakingCancelled acknowledges leaving the queue. Also sent when the
  // server drops somebody from it (a pairing that fell apart before it began).
  | 'matchmaking_cancelled'
  // SMsgMatchFound seats both players at once. It carries everything
  // room_joined carries, plus StartsInMs: the match deals itself after that
  // delay, and nobody has to press anything.
  | 'match_found'
  // SMsgLeftRoom acknowledges leave_room. The client is seatless again and
  // back on the home screen.
  | 'left_room'
  // SMsgHostChanged announces the table's new owner after a transfer_host.
  // Sent per-recipient, like SMsgRematchStarted and for the same reason: the
  // swap moves two seats, so half the room's own player_id changes with it and
  // a broadcast would leave the two players who moved reading somebody else's
  // row as their own. Nickname names the new host, Players carries the roster
  // in its new order, PlayerID the recipient's own seat.
  | 'host_changed'
  // SMsgKicked tells a client the host freed its seat. Everything left_room
  // means — seatless, back home — plus the one thing the player did not
  // choose, so the screen changing under them is explained rather than
  // mysterious. Sent to the removed client only; the table sees player_left.
  | 'kicked'
  // SMsgMatchLoading is sent right after game_started while the table waits for
  // everybody to finish downloading the map, and again on each arrival so the
  // loading screen can show who is still missing. PlayersReady names the seats
  // that are in.
  | 'match_loading'
  // SMsgMatchReady releases the table: the clock starts here, not at
  // game_started. Carries the turn deadline armed in the same instant.
  | 'match_ready'
  // Gameplay state
  | 'game_state'
  | 'card_played'
  | 'card_drawn'
  | 'turn_changed'
  | 'uno_declared'
  | 'uno_caught'
  // SMsgCatchFailed names the seat whose Contre-LOCO! arrived too late and was
  // charged a card for it. Broadcast to the whole room: the wager is public,
  // like the catch it lost to.
  | 'catch_failed'
  | 'interrupt_success'
  // Round / match lifecycle
  | 'round_end'
  | 'match_end'
  // SMsgLatency carries every seat's measured round-trip time. Broadcast on a
  // timer to rooms that are playing, so the in-game score table can show a
  // live ping per player without any client self-reporting.
  | 'latency'
  // SMsgRematchOffered names a seat that has asked for another match. In a
  // matchmade room a rematch is an agreement between two strangers rather than
  // a host's decision, so both offers are public: the player who has not
  // answered yet needs to know somebody is waiting on them.
  | 'rematch_offered'
  // SMsgRematchStarted tells every remaining member that the finished room is
  // back in the lobby. Sent per-recipient because pruning absent players can
  // shift player indices.
  | 'rematch_started'
  // SMsgServerUpdating tells a table in progress that this process is being
  // replaced. It is information, not an instruction: the match plays out to
  // its end, and nothing about it changes. Sent once, when the drain starts,
  // and again to anyone who reconnects into a draining server.
  | 'server_updating'
  // Errors
  | 'error'

// ClientMsg is the envelope for all client-to-server messages.
export interface ClientMsg {
  type: ClientMsgType
  // CMsgCreateRoom / CMsgJoinRoom
  nickname?: string
  room_code?: string
  // CMsgJoinRoom reconnect: prove identity
  session_token?: string
  // CMsgPlayCard / CMsgCounterDraw
  card?: CardDTO
  chosen_color?: CardColor
  chosen_player?: number // target player index for Swap cards
  // CMsgPlayCard batch: when the player plays multiple identical cards at once.
  // All cards must be exactly equal; if PlayCards is non-empty it takes precedence
  // over the singular Card field. Swap and GlobalSwitch cannot be batch-played.
  play_cards?: CardDTO[]
  // CMsgPlayCard / CMsgInterruptPlay batch: the LOCO! call the play carries.
  //
  // Only read when the batch empties the hand, which is the one finish the
  // player had no chance to announce beforehand: a hand of two identical cards
  // put down at once never passes through one card, so no catch window ever
  // opened on it and no declaration was ever possible. The server refuses such
  // a batch without this flag (game.ErrMustDeclareLoco). Every other finish is
  // gated on a declaration that already happened, and ignores this field.
  declare_loco?: boolean
  // CMsgCatchUno: which seat is being caught. Several players can owe a
  // declaration at once (Swap / GlobalSwitch hand a single card to more than
  // one of them), so the catcher names their target. Omitted = the window
  // closest to expiring.
  //
  // CMsgKickPlayer: which seat the host is freeing. Required there — there is
  // no sensible default seat to remove.
  //
  // CMsgTransferHost: which seat is being handed the table. Required there too,
  // and for the same reason.
  target_index?: number
  // CMsgSetMatchFormat
  match_format?: MatchFormat
  // CMsgSetMaxPlayers
  max_players?: number
  // CMsgDebugSetState — dev/E2E only (guarded by LOCO_E2E=1 server env var).
  //
  // One pointer, not seven fields. This struct is every message a client can
  // send, so seven flattened fixture fields were carried by play_card and
  // catch_uno too, and a reader of ClientMsg had to know which of the twenty
  // fields in front of them belonged to a message no player's client ever
  // sends. Nested, the fixture is one nil check away from the wire protocol
  // and reads as what it is: a dev-only payload hanging off a dev-only type.
  debug?: DebugStateDTO
}

// DebugStateDTO is the whole payload of debug_set_state. Any combination of
// fields may be provided; omitted fields leave that part of the state alone.
export interface DebugStateDTO {
  hand?: CardDTO[] // replace this player's hand
  hands?: DebugHandOverrideDTO[] // replace arbitrary players' hands
  discard?: CardDTO // replace top of discard pile
  active_color?: CardColor // override active color
  pending_draw?: number // override pending draw count
  current_turn?: number // override current turn player index
  direction?: number // override play direction (1 cw, -1 ccw)
}

// DebugHandOverrideDTO is one per-player hand replacement used by debug_set_state.
export interface DebugHandOverrideDTO {
  player_index: number
  hand: CardDTO[]
}

// CardDTO is the wire representation of a card.
export interface CardDTO {
  color: CardColor
  kind: CardKind
  value?: number
}

// CatchSeatDTO names a seat that owes the table a declaration, and says when
// its window shuts. EndsAt is unix milliseconds, like every other deadline on
// the wire, so a client renders a countdown against its own clock rather than
// holding a copy of the server's window length.
export interface CatchSeatDTO {
  player_index: number
  ends_at: number
}

// ScoreboardEntryDTO is one player's match-level score summary.
export interface ScoreboardEntryDTO {
  player_index: number
  nickname: string
  score: number
  rounds_won: number
}

// LatencyEntryDTO is one seat's measured round-trip time.
export interface LatencyEntryDTO {
  player_index: number
  // RTTMs is the smoothed WebSocket ping/pong round trip in milliseconds,
  // or -1 when nothing has been measured yet (bots, a seat that just
  // connected, a player inside their reconnect window).
  rtt_ms: number
  bot?: boolean
}

// ServerMsg is the envelope for all server-to-client messages.
export interface ServerMsg {
  type: ServerMsgType
  // SMsgRoomCreated / SMsgRoomJoined / SMsgPlayerReconnected (self) /
  // SMsgRematchStarted: the recipient's OWN seat.
  //
  // A pointer for exactly the same reason as PlayerIndex below, and it took
  // longer to notice because the client's `?? 0` fallback was right by luck
  // everywhere it mattered: the host is seat 0 on room_created, so an absent
  // field and the default agreed. A tab reloading into a match is where the
  // luck runs out: it has no earlier value to fall back to, so a dropped
  // player_id left the restored client seated at -1, holding a hand it could
  // not match to any seat on the board. Read it with OwnSeat().
  room_code?: string
  player_id?: number
  session_token?: string // opaque token for reconnect auth
  // Player lists and nicknames
  players?: PlayerDTO[]
  nickname?: string
  // SMsgGameStarted / SMsgGameState / SMsgPlayerReconnected (self)
  state?: GameStateDTO
  // SMsgCardPlayed / SMsgCardDrawn / SMsgUnoDeclared / SMsgUnoCaught /
  // SMsgCatchFailed / SMsgInterruptSuccess / SMsgPlayerDisconnected /
  // SMsgPlayerReconnected:
  // the seat the message is about.
  //
  // A pointer for the same reason as PendingDraw/HasDrawn below: `omitempty`
  // drops a zero, and seat 0 is the host's seat. The client closes the catch
  // window on the seat named by uno_declared, so an absent player_index left
  // it open — Contre-LOCO! stayed armed on a player who had already called it
  // and the server refused every tap with "player already declared".
  // Read it with Seat(); absent means "this message names no seat".
  player_index?: number
  card?: CardDTO
  active_color?: CardColor // authoritative active color after card play
  // Set only when a Swap card resolves: the target player index whose hand was exchanged
  // with the actor's hand. Lets clients show a "X swapped with Y" notification without
  // exposing hand contents to non-participants.
  chosen_player?: number
  // SMsgTurnChanged.
  //
  // No omitempty, deliberately: seat 0 is a turn like any other, and dropping
  // it would leave every client to infer whose turn it is from an absence.
  // The client happens to default to 0, so this was correct by luck — the same
  // luck PlayerIndex did not have. A few bytes on every message is the price of
  // never having to think about it again.
  turn?: number
  // Play direction (1 = clockwise, -1 = counter-clockwise) AFTER any card effect
  // has been applied. Included in card_played so clients can update their
  // direction indicator immediately without waiting for the next game_state.
  direction?: number
  // Per-turn deadline: unix milliseconds when the current turn expires (0 = no timer active)
  // Included in card_played, card_drawn, turn_changed, and game_started to let clients
  // display and reset the countdown when a new turn begins.
  turn_deadline?: number
  // SMsgCardPlayed: every seat that owes the table a declaration once this
  // play has resolved, with the instant each window shuts.
  //
  // The server sends it because the server decides it. The client used to work
  // it out again from the roster and the card kind (an ordinary play puts the
  // actor on the hook, a Swap or a GlobalSwitch puts every seat left holding
  // one card on it), which is the server's rule living in two places, in two
  // languages, with nothing checking they agree. A drift there does not fail,
  // it just arms Contre-LOCO! on a tap the server will refuse, or leaves it
  // dark on a seat the player was entitled to catch.
  catch_seats?: CatchSeatDTO[]
  // SMsgCardPlayed / SMsgCardDrawn: the authoritative turn state AFTER the
  // event.
  //
  // Pointers, not plain values: `omitempty` drops a false bool and a zero int
  // from the wire, so the receiver has to invent the missing value — and it
  // guesses wrong exactly where it hurts. A hand can grow without the current
  // player having drawn (UNO-catch penalty), and a client that read the absent
  // has_drawn as "true" then disabled its own Draw button and had every Pass
  // refused with "you must draw a card before passing" until the turn timer
  // bailed it out. Absent now means "unchanged", and every sender fills them in.
  pending_draw?: number
  has_drawn?: boolean
  // SMsgCardDrawn: multiple cards drawn at once (penalty draw)
  // Cards holds all drawn cards for the drawing player; DrawnCount tells observers how many.
  //
  // A slice of values, not of pointers. `[]*CardDTO` says a slot can be null,
  // which the server has never produced and no client has ever handled, and it
  // has no honest TypeScript spelling: the generator would have had to either
  // invent `(CardDTO | null)[]` for a case that cannot arise, or quietly drop
  // the nullability and be stricter than the wire. Neither is a decision worth
  // leaving to a code generator.
  cards?: CardDTO[]
  // No omitempty for the same reason as Turn, and here it was not luck: a draw
  // against exhausted piles hands over nothing, and the client's fallback for
  // an absent count was 1 — so every observer would have added a card nobody
  // drew, to a hand the server never grew.
  drawn_count?: number
  // SMsgRoundEnd / SMsgMatchEnd
  round_number?: number
  round_winner?: string
  scoreboard?: ScoreboardEntryDTO[]
  match_over?: boolean
  match_winner?: string
  // SMsgMatchEnd: this match ended because somebody stopped being there, not
  // because a round was won. PlayerIndex above names the seat that left, so
  // the survivor's screen can say what happened instead of celebrating a
  // victory nobody played for. Absent means an ordinary end, the one thing an
  // omitted bool can mean here, since the field rides a single message type.
  forfeit?: boolean
  // SMsgPlayerDisconnected: unix milliseconds at which the absent seat's match
  // is forfeited if they have not come back. Only sent for matchmade rooms,
  // where the wait is short and the player still at the table is owed a number
  // rather than an indefinite "opponent disconnected". 0/absent = no such
  // deadline (an ordinary room, where the seat is simply held).
  forfeit_deadline?: number
  // SMsgMatchFound: how long the reveal lasts before the match deals itself.
  // Absent means "immediately", which is the right reading: the countdown is
  // presentation, and game_started arriving is what actually opens the match.
  starts_in_ms?: number
  // RoundHistory[k][playerIndex] = points scored in round k+1. Sent with
  // round_end so the score table updates without waiting for the next
  // game_state (which the client buffers behind the round summary).
  round_history?: number[][]
  // SMsgLatency
  latencies?: LatencyEntryDTO[]
  // SMsgLobbyConfigChanged
  match_format?: MatchFormat
  max_players?: number
  // SMsgMatchLoading: the seats whose client has the map decoded.
  //
  // `omitempty` is safe here, unlike on PlayerIndex/PendingDraw: this field
  // appears on exactly one message type, so an absent list can only mean "no
  // seat is ready yet": there is no earlier value it could be leaving
  // unchanged. Keeping it omittable also keeps it off every other broadcast.
  players_ready?: number[]
  // SMsgRematchOffered: every seat that has asked for another match, and how
  // many asks it takes. The whole state travels rather than the increment,
  // because a seat leaving retires its offer and re-bases the rest: a client
  // accumulating names would keep a departed player's ask forever.
  //
  // A pointer for the same reason PlayerIndex is one: this list has to be able
  // to say "nobody is asking any more", and an empty slice under `omitempty`
  // marshals to nothing, which every other message would then also carry as
  // "no offers" and which the client could not tell from "unchanged".
  // Read it with Offers().
  rematch_offers?: number[]
  // RematchNeeded is how many of those asks deal the next match: every human
  // still at the table. Bots are not asked.
  rematch_needed?: number
  // SMsgError
  error?: string
}

// PlayerDTO is the public view of a player.
export interface PlayerDTO {
  index: number
  nickname: string
  hand_size: number
  connected: boolean
  // IsBot marks a seat the server plays. Carried because the roster offers
  // controls a bot cannot answer — the table cannot be handed to one — and the
  // nickname is not a way to tell: "Bot1" is a name a player is allowed to
  // take.
  //
  // omitempty, unlike Connected: absent and false are the same statement here,
  // where an absent `connected` would be a player the roster stopped
  // mentioning. Most seats are people, so most rosters carry it for none of
  // them.
  is_bot?: boolean
}

// GameEventDTO is the wire representation of a game event.
export interface GameEventDTO {
  // Kind stays a bare string, unlike CardDTO.Kind: these are event kinds from
  // the domain's own log, they are read only as labels, and a server that logs
  // a new one must not make a generated client refuse the whole snapshot.
  kind: string
  player_index: number
  card?: CardDTO
  chosen_color?: CardColor
  at: number // unix milliseconds
}

// GameStateDTO is the per-player view of the game state sent on join/start.
export interface GameStateDTO {
  your_index: number
  hand: CardDTO[]
  players: PlayerDTO[]
  discard: CardDTO
  active_color: CardColor
  turn: number
  direction: number
  pending_draw?: number
  has_drawn?: boolean
  event_log?: GameEventDTO[]
  // Match info
  round_number: number
  match_format: MatchFormat
  max_players: number
  // MapID names the room this match is played in (see game/maps.go). Rides
  // every snapshot rather than only game_started so a reconnecting player
  // rebuilds the same table as everybody else. Empty = the built-in felt.
  map_id?: string
  scoreboard?: ScoreboardEntryDTO[]
  // RoundHistory[k][playerIndex] = points scored in round k+1 (see ServerMsg).
  // Included in every snapshot so a reconnecting player recovers the table.
  round_history?: number[][]
  // Per-turn deadline: unix milliseconds when the current turn expires (0 = no timer active)
  turn_deadline?: number
}
