// Code generated by server/cmd/protocolgen. DO NOT EDIT.
//
// Source: server/protocol. Regenerate with "make protocol"; CI fails the build if
// this file and the Go source have drifted apart, so editing it by hand is
// undone by the next run rather than merged.
//
// This file carries the inbound validation schemas.

import * as v from 'valibot'

// CardColor is a card colour, or the table's active colour, as it travels.
// ColorWild is what a wild card carries before its owner names a real one; it
// must never reach a game state's active colour.
export const cardColorSchema = v.picklist([
  'red',
  'yellow',
  'green',
  'blue',
  'wild',
])

// CardKind is a card's kind as it travels. KindWild is the plain wild card;
// KindGlobalSwitch is LOCO's own, a wild that rotates every hand.
export const cardKindSchema = v.picklist([
  'number',
  'skip',
  'reverse',
  'draw_two',
  'wild',
  'wild_draw_four',
  'swap',
  'global_switch',
])

// MatchFormat is the best-of-N format a table is playing.
export const matchFormatSchema = v.picklist([
  'BO1',
  'BO3',
  'BO5',
  'BO7',
])

// Emote is one of the three things a player can say at the end of a match, and
// the whole vocabulary the game has.
//
// A closed set, decided here and travelling as an identifier, because the
// alternative is free text — and free text is a moderation surface, which is a
// promise this game cannot keep: "we collect nothing" is the compliance
// strategy, not an accident. Three is enough to be gracious and too few to be
// abusive, which is the only property that matters.
//
// The words themselves are the client's (`t.emotes`), in the player's own
// language. Nothing here is stored, logged or snapshotted: an emote is
// broadcast, shown for a few seconds, and forgotten.
export const emoteSchema = v.picklist([
  'gg',
  'close',
  'nice',
])

// ClientMsgType enumerates message types sent from client to server.
export const clientMsgTypeSchema = v.picklist([
  'create_room',
  'join_room',
  'start_game',
  'add_bot',
  'set_match_format',
  'set_max_players',
  'set_streamer_mode',
  'kick_player',
  'transfer_host',
  'rematch',
  'send_emote',
  'find_match',
  'cancel_matchmaking',
  'play_bot',
  'leave_room',
  'play_card',
  'draw_card',
  'pass_turn',
  'declare_uno',
  'catch_uno',
  'counter_draw',
  'map_ready',
  'interrupt_play',
  'interrupt_play_card',
  'debug_set_state',
])

// ServerMsgType enumerates message types sent from server to client.
export const serverMsgTypeSchema = v.picklist([
  'room_created',
  'room_joined',
  'player_joined',
  'player_left',
  'player_disconnected',
  'player_reconnected',
  'lobby_config_changed',
  'streamer_mode_changed',
  'game_started',
  'matchmaking_queued',
  'matchmaking_cancelled',
  'match_found',
  'left_room',
  'host_changed',
  'kicked',
  'match_loading',
  'match_ready',
  'game_state',
  'card_played',
  'card_drawn',
  'turn_changed',
  'uno_declared',
  'uno_caught',
  'catch_failed',
  'interrupt_success',
  'round_end',
  'match_end',
  'latency',
  'emote',
  'rematch_offered',
  'rematch_started',
  'players_online',
  'server_updating',
  'error',
])

// CardDTO is the wire representation of a card.
export const cardSchema = v.object({
  color: cardColorSchema,
  kind: cardKindSchema,
  value: v.optional(v.number()),
})

// DebugHandOverrideDTO is one per-player hand replacement used by debug_set_state.
export const debugHandOverrideSchema = v.object({
  player_index: v.number(),
  hand: v.array(cardSchema),
})

// DebugStateDTO is the whole payload of debug_set_state. Any combination of
// fields may be provided; omitted fields leave that part of the state alone.
export const debugStateSchema = v.object({
  hand: v.optional(v.array(cardSchema)),
  hands: v.optional(v.array(debugHandOverrideSchema)),
  discard: v.optional(cardSchema),
  active_color: v.optional(cardColorSchema),
  pending_draw: v.optional(v.number()),
  current_turn: v.optional(v.number()),
  direction: v.optional(v.number()),
})

// ClientMsg is the envelope for all client-to-server messages.
export const clientMsgSchema = v.object({
  type: clientMsgTypeSchema,
  // CMsgCreateRoom / CMsgJoinRoom
  nickname: v.optional(v.string()),
  room_code: v.optional(v.string()),
  // CMsgJoinRoom reconnect: prove identity
  session_token: v.optional(v.string()),
  // CMsgPlayCard / CMsgCounterDraw
  card: v.optional(cardSchema),
  chosen_color: v.optional(cardColorSchema),
  chosen_player: v.optional(v.number()),
  // CMsgPlayCard batch: when the player plays multiple identical cards at once.
  // All cards must be exactly equal; if PlayCards is non-empty it takes precedence
  // over the singular Card field. Swap and GlobalSwitch cannot be batch-played.
  play_cards: v.optional(v.array(cardSchema)),
  // CMsgPlayCard / CMsgInterruptPlay batch: the LOCO! call the play carries.
  //
  // Only read when the batch empties the hand, which is the one finish the
  // player had no chance to announce beforehand: a hand of two identical cards
  // put down at once never passes through one card, so no catch window ever
  // opened on it and no declaration was ever possible. The server refuses such
  // a batch without this flag (game.ErrMustDeclareLoco). Every other finish is
  // gated on a declaration that already happened, and ignores this field.
  declare_loco: v.optional(v.boolean()),
  // CMsgCatchUno: which seat is being caught. Several players can owe a
  // declaration at once (Swap / GlobalSwitch hand a single card to more than
  // one of them), so the catcher names their target. Omitted = the window
  // closest to expiring.
  //
  // CMsgKickPlayer: which seat the host is freeing. Required there — there is
  // no sensible default seat to remove.
  //
  // CMsgTransferHost: which seat is being handed the table. Required there too,
  // and for the same reason.
  target_index: v.optional(v.number()),
  // CMsgSetMatchFormat
  match_format: v.optional(matchFormatSchema),
  // CMsgSetMaxPlayers
  max_players: v.optional(v.number()),
  // CMsgSetStreamerMode: the state the host is asking for, not a toggle. A
  // toggle would come back wrong from a client whose picture of the table is a
  // message behind, and this one is switched from a panel that can be opened on
  // any screen.
  //
  // `omitempty` costs nothing here because absent and false mean the same
  // thing — off — on the one message type that reads it. That is not true of
  // the seat and turn fields above, whose zero is a seat.
  streamer_mode: v.optional(v.boolean()),
  // CMsgSendEmote: which of the three. Validated against AllEmotes, so an
  // identifier this server does not know is refused rather than relayed.
  emote: v.optional(emoteSchema),
  // CMsgDebugSetState — dev/E2E only (guarded by LOCO_E2E=1 server env var).
  //
  // One pointer, not seven fields. This struct is every message a client can
  // send, so seven flattened fixture fields were carried by play_card and
  // catch_uno too, and a reader of ClientMsg had to know which of the twenty
  // fields in front of them belonged to a message no player's client ever
  // sends. Nested, the fixture is one nil check away from the wire protocol
  // and reads as what it is: a dev-only payload hanging off a dev-only type.
  debug: v.optional(debugStateSchema),
})

// CatchSeatDTO names a seat that owes the table a declaration, and says when
// its window shuts. EndsAt is unix milliseconds, like every other deadline on
// the wire, so a client renders a countdown against its own clock rather than
// holding a copy of the server's window length.
export const catchSeatSchema = v.object({
  player_index: v.number(),
  ends_at: v.number(),
})

// ScoreboardEntryDTO is one player's match-level score summary.
export const scoreboardEntrySchema = v.object({
  player_index: v.number(),
  nickname: v.string(),
  score: v.number(),
  rounds_won: v.number(),
})

// MatchRecordDTO is one finished match at this table, kept so a group playing
// six in a row can see who actually won the evening.
//
// Both halves travel because both are read: RoundsWon is what decided that
// match, Scores is the gap it was decided by. Indexed by seat, exactly like the
// scoreboard, so a client renders one column per match against the roster it
// already has.
export const matchRecordSchema = v.object({
  rounds_won: v.array(v.number()),
  scores: v.array(v.number()),
  // WinnerIndex is the seat that took the match, or -1 when the seat that took
  // it has since left the table. No omitempty: seat 0 is a winner like any
  // other, and dropping it would hand the match to nobody.
  winner_index: v.number(),
})

// LatencyEntryDTO is one seat's measured round-trip time.
export const latencyEntrySchema = v.object({
  player_index: v.number(),
  // RTTMs is the smoothed WebSocket ping/pong round trip in milliseconds,
  // or -1 when nothing has been measured yet (bots, a seat that just
  // connected, a player inside their reconnect window).
  rtt_ms: v.number(),
  bot: v.optional(v.boolean()),
})

// PlayerDTO is the public view of a player.
export const playerSchema = v.object({
  index: v.number(),
  nickname: v.string(),
  hand_size: v.number(),
  connected: v.boolean(),
  // IsBot marks a seat the server plays. Carried because the roster offers
  // controls a bot cannot answer — the table cannot be handed to one — and the
  // nickname is not a way to tell: "Bot1" is a name a player is allowed to
  // take.
  //
  // omitempty, unlike Connected: absent and false are the same statement here,
  // where an absent `connected` would be a player the roster stopped
  // mentioning. Most seats are people, so most rosters carry it for none of
  // them.
  is_bot: v.optional(v.boolean()),
})

// GameEventDTO is the wire representation of a game event.
export const gameEventSchema = v.object({
  // Kind stays a bare string, unlike CardDTO.Kind: these are event kinds from
  // the domain's own log, they are read only as labels, and a server that logs
  // a new one must not make a generated client refuse the whole snapshot.
  kind: v.string(),
  player_index: v.number(),
  card: v.optional(cardSchema),
  chosen_color: v.optional(cardColorSchema),
  at: v.number(),
})

// GameStateDTO is the per-player view of the game state sent on join/start.
export const gameStateSchema = v.object({
  your_index: v.number(),
  hand: v.array(cardSchema),
  players: v.array(playerSchema),
  discard: cardSchema,
  active_color: cardColorSchema,
  turn: v.number(),
  direction: v.number(),
  pending_draw: v.optional(v.number()),
  has_drawn: v.optional(v.boolean()),
  event_log: v.optional(v.array(gameEventSchema)),
  // Match info
  round_number: v.number(),
  match_format: matchFormatSchema,
  max_players: v.number(),
  // MapID names the room this match is played in (see game/maps.go). Rides
  // every snapshot rather than only game_started so a reconnecting player
  // rebuilds the same table as everybody else. Empty = the built-in felt.
  map_id: v.optional(v.string()),
  scoreboard: v.optional(v.array(scoreboardEntrySchema)),
  // RoundHistory[k][playerIndex] = points scored in round k+1 (see ServerMsg).
  // Included in every snapshot so a reconnecting player recovers the table.
  round_history: v.optional(v.array(v.array(v.number()))),
  // MatchHistory is the table's finished matches (see ServerMsg). Carried here
  // too so a player who reconnects mid-match still has the evening behind them
  // when this match ends.
  match_history: v.optional(v.array(matchRecordSchema)),
  // Per-turn deadline: unix milliseconds when the current turn expires (0 = no timer active)
  turn_deadline: v.optional(v.number()),
  // StreamerMode is the host's answer, carried in every snapshot for the same
  // reason MapID is: a tab that reloads mid-match rebuilds the table from this
  // and nothing else, and a table code that comes back readable on a stream is
  // the one failure this setting exists to prevent. See ServerMsg.StreamerMode.
  streamer_mode: v.optional(v.boolean()),
})

// ServerMsg is the envelope for all server-to-client messages.
export const serverMsgSchema = v.object({
  type: serverMsgTypeSchema,
  // SMsgRoomCreated / SMsgRoomJoined / SMsgPlayerReconnected (self) /
  // SMsgRematchStarted: the recipient's OWN seat.
  //
  // A pointer for exactly the same reason as PlayerIndex below, and it took
  // longer to notice because the client's `?? 0` fallback was right by luck
  // everywhere it mattered: the host is seat 0 on room_created, so an absent
  // field and the default agreed. A tab reloading into a match is where the
  // luck runs out: it has no earlier value to fall back to, so a dropped
  // player_id left the restored client seated at -1, holding a hand it could
  // not match to any seat on the board. Read it with OwnSeat().
  room_code: v.optional(v.string()),
  player_id: v.optional(v.number()),
  session_token: v.optional(v.string()),
  // Player lists and nicknames
  players: v.optional(v.array(playerSchema)),
  nickname: v.optional(v.string()),
  // SMsgGameStarted / SMsgGameState / SMsgPlayerReconnected (self)
  state: v.optional(gameStateSchema),
  // SMsgCardPlayed / SMsgCardDrawn / SMsgUnoDeclared / SMsgUnoCaught /
  // SMsgCatchFailed / SMsgInterruptSuccess / SMsgPlayerDisconnected /
  // SMsgPlayerReconnected:
  // the seat the message is about.
  //
  // A pointer for the same reason as PendingDraw/HasDrawn below: `omitempty`
  // drops a zero, and seat 0 is the host's seat. The client closes the catch
  // window on the seat named by uno_declared, so an absent player_index left
  // it open — Contre-LOCO! stayed armed on a player who had already called it
  // and the server refused every tap with "player already declared".
  // Read it with Seat(); absent means "this message names no seat".
  player_index: v.optional(v.number()),
  card: v.optional(cardSchema),
  active_color: v.optional(cardColorSchema),
  // Set only when a Swap card resolves: the target player index whose hand was exchanged
  // with the actor's hand. Lets clients show a "X swapped with Y" notification without
  // exposing hand contents to non-participants.
  chosen_player: v.optional(v.number()),
  // SMsgTurnChanged.
  //
  // No omitempty, deliberately: seat 0 is a turn like any other, and dropping
  // it would leave every client to infer whose turn it is from an absence.
  // The client happens to default to 0, so this was correct by luck — the same
  // luck PlayerIndex did not have. A few bytes on every message is the price of
  // never having to think about it again.
  turn: v.optional(v.number()),
  // Play direction (1 = clockwise, -1 = counter-clockwise) AFTER any card effect
  // has been applied. Included in card_played so clients can update their
  // direction indicator immediately without waiting for the next game_state.
  direction: v.optional(v.number()),
  // Per-turn deadline: unix milliseconds when the current turn expires (0 = no timer active)
  // Included in card_played, card_drawn, turn_changed, and game_started to let clients
  // display and reset the countdown when a new turn begins.
  turn_deadline: v.optional(v.number()),
  // SMsgCardPlayed: every seat that owes the table a declaration once this
  // play has resolved, with the instant each window shuts.
  //
  // The server sends it because the server decides it. The client used to work
  // it out again from the roster and the card kind (an ordinary play puts the
  // actor on the hook, a Swap or a GlobalSwitch puts every seat left holding
  // one card on it), which is the server's rule living in two places, in two
  // languages, with nothing checking they agree. A drift there does not fail,
  // it just arms Contre-LOCO! on a tap the server will refuse, or leaves it
  // dark on a seat the player was entitled to catch.
  catch_seats: v.optional(v.array(catchSeatSchema)),
  // SMsgCardPlayed / SMsgCardDrawn: the authoritative turn state AFTER the
  // event.
  //
  // Pointers, not plain values: `omitempty` drops a false bool and a zero int
  // from the wire, so the receiver has to invent the missing value — and it
  // guesses wrong exactly where it hurts. A hand can grow without the current
  // player having drawn (UNO-catch penalty), and a client that read the absent
  // has_drawn as "true" then disabled its own Draw button and had every Pass
  // refused with "you must draw a card before passing" until the turn timer
  // bailed it out. Absent now means "unchanged", and every sender fills them in.
  pending_draw: v.optional(v.number()),
  has_drawn: v.optional(v.boolean()),
  // SMsgCardDrawn: multiple cards drawn at once (penalty draw)
  // Cards holds all drawn cards for the drawing player; DrawnCount tells observers how many.
  //
  // A slice of values, not of pointers. `[]*CardDTO` says a slot can be null,
  // which the server has never produced and no client has ever handled, and it
  // has no honest TypeScript spelling: the generator would have had to either
  // invent `(CardDTO | null)[]` for a case that cannot arise, or quietly drop
  // the nullability and be stricter than the wire. Neither is a decision worth
  // leaving to a code generator.
  cards: v.optional(v.array(cardSchema)),
  // No omitempty for the same reason as Turn, and here it was not luck: a draw
  // against exhausted piles hands over nothing, and the client's fallback for
  // an absent count was 1 — so every observer would have added a card nobody
  // drew, to a hand the server never grew.
  drawn_count: v.optional(v.number()),
  // SMsgRoundEnd / SMsgMatchEnd
  round_number: v.optional(v.number()),
  round_winner: v.optional(v.string()),
  scoreboard: v.optional(v.array(scoreboardEntrySchema)),
  match_over: v.optional(v.boolean()),
  match_winner: v.optional(v.string()),
  // SMsgMatchEnd: this match ended because somebody stopped being there, not
  // because a round was won. PlayerIndex above names the seat that left, so
  // the survivor's screen can say what happened instead of celebrating a
  // victory nobody played for. Absent means an ordinary end, the one thing an
  // omitted bool can mean here, since the field rides a single message type.
  forfeit: v.optional(v.boolean()),
  // SMsgPlayerDisconnected: unix milliseconds at which the absent seat's match
  // is forfeited if they have not come back. Only sent for matchmade rooms,
  // where the wait is short and the player still at the table is owed a number
  // rather than an indefinite "opponent disconnected". 0/absent = no such
  // deadline (an ordinary room, where the seat is simply held).
  forfeit_deadline: v.optional(v.number()),
  // SMsgMatchFound: how long the reveal lasts before the match deals itself.
  // Absent means "immediately", which is the right reading: the countdown is
  // presentation, and game_started arriving is what actually opens the match.
  starts_in_ms: v.optional(v.number()),
  // RoundHistory[k][playerIndex] = points scored in round k+1. Sent with
  // round_end so the score table updates without waiting for the next
  // game_state (which the client buffers behind the round summary).
  round_history: v.optional(v.array(v.array(v.number()))),
  // SMsgMatchEnd: every match this table has finished, oldest first, the one
  // just ended included. A rematch wipes the scoreboard, so without this a
  // group that plays six matches on one code ends the evening with nobody able
  // to say who won it. Only the game-over screen reads it, so it rides the one
  // message that opens that screen.
  //
  // SMsgPlayerLeft carries it too, and only on the departures that re-base the
  // roster: every row is indexed by seat, so a screen that is already up is
  // reading the wrong column the moment a seat below it goes.
  match_history: v.optional(v.array(matchRecordSchema)),
  // SMsgLatency
  latencies: v.optional(v.array(latencyEntrySchema)),
  // SMsgLobbyConfigChanged
  match_format: v.optional(matchFormatSchema),
  max_players: v.optional(v.number()),
  // SMsgStreamerModeChanged, and the table's current answer on SMsgRoomJoined so
  // somebody arriving mid-stream blurs the code without waiting for the host to
  // touch the switch again. (Not on SMsgRoomCreated: that table is one message
  // old and the host is the client that owns the setting.)
  //
  // `omitempty` for the same reason as Forfeit: absent can only mean off. The
  // field rides message types that always carry the whole state of the setting,
  // never an increment, so there is no earlier value it could be leaving
  // unchanged.
  streamer_mode: v.optional(v.boolean()),
  // SMsgMatchLoading: the seats whose client has the map decoded.
  //
  // `omitempty` is safe here, unlike on PlayerIndex/PendingDraw: this field
  // appears on exactly one message type, so an absent list can only mean "no
  // seat is ready yet": there is no earlier value it could be leaving
  // unchanged. Keeping it omittable also keeps it off every other broadcast.
  players_ready: v.optional(v.array(v.number())),
  // SMsgRematchOffered: every seat that has asked for another match, and how
  // many asks it takes. The whole state travels rather than the increment,
  // because a seat leaving retires its offer and re-bases the rest: a client
  // accumulating names would keep a departed player's ask forever.
  //
  // A pointer for the same reason PlayerIndex is one: this list has to be able
  // to say "nobody is asking any more", and an empty slice under `omitempty`
  // marshals to nothing, which every other message would then also carry as
  // "no offers" and which the client could not tell from "unchanged".
  // Read it with Offers().
  rematch_offers: v.optional(v.array(v.number())),
  // RematchNeeded is how many of those asks deal the next match: two, one
  // offering and one accepting, or the whole table when it is smaller than
  // that. Bots are not asked. See hub.RematchQuorum.
  rematch_needed: v.optional(v.number()),
  // SMsgEmote: what was said, and PlayerIndex above says who said it.
  emote: v.optional(emoteSchema),
  // SMsgPlayersOnline: how many sockets this server is holding.
  //
  // A pointer, like PlayerIndex and for both of its reasons. The number that
  // most has to reach the home screen is the one that has just dropped, and a
  // plain int under `omitempty` drops a zero — the chip would stay on screen
  // counting people who have gone. Spelling it without `omitempty` instead
  // would put `players_online: 0` on every card_played this server sends, for
  // a field one screen reads and no match ever does.
  players_online: v.optional(v.number()),
  // SMsgError
  error: v.optional(v.string()),
})
