/**
 * The page an invitation points at, and the four things that make it work.
 *
 * `/i/?t=CODE` is a page the build emitted and a query parameter on it, and that
 * is a decision this file exists to keep: a path form (`/i/CODE`) is not a page,
 * so it would need a fallback in whoever serves the request — which nginx can do
 * and `astro dev` cannot, leaving a URL that resolves in production and 404s
 * under `make dev` and the entire Playwright suite.
 *
 * The rest is the discipline a duplicate of the home page owes the index:
 * noindex, no sitemap entry, no hreflang, no canonical, no second `#webpage`.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { INVITE, INVITE_OG, OG_IMAGE, PAGES, NAV, LANGS } from '../seo/meta'
import { tableInviteUrl } from '../hooks/tableInvite'

const CLIENT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const read = (...p: string[]) => readFileSync(path.join(CLIENT, ...p), 'utf8')

const nginx = read('nginx.conf')
const astroConfig = read('astro.config.mjs')
const pageSource = read('src', 'pages', 'i', 'index.astro')

describe('the invite page', () => {
  it('is one path in both languages, because an invitation carries no language', () => {
    // The link is forwarded and the sender does not know who opens it. A French
    // twin would be a second URL to choose between with nothing to choose on.
    const paths = new Set(LANGS.map((l) => INVITE.path[l]))
    expect(paths.size).toBe(1)
    expect(INVITE.path.en).toBe('/i/')
  })

  it('is served by a real file', () => {
    expect(existsSync(path.join(CLIENT, 'src', 'pages', 'i', 'index.astro'))).toBe(true)
  })

  it('is noindex, and carries no chrome and no structured data', () => {
    // Each of the four is load-bearing: noindex keeps a duplicate of the home
    // page out of the index (and out of the canonical graph with it), chrome
    // would put five links and a page of prose under a table somebody was
    // invited to, jsonLd={null} stops a second #webpage node describing the game
    // at a second URL, and langNeutral is what keeps initLang from moving the
    // address bar away from an invitation it has no opinion about.
    expect(pageSource).toMatch(/\bnoindex\b/)
    expect(pageSource).toMatch(/chrome=\{false\}/)
    expect(pageSource).toMatch(/jsonLd=\{null\}/)
    expect(pageSource).toMatch(/\blangNeutral\b/)
    expect(pageSource).toMatch(/page=\{INVITE\}/)
  })

  it('is in no navigation and no hreflang set', () => {
    // `PAGES` is what the alternates and seo.test.ts read. A door somebody was
    // handed is not a page anybody should arrive at cold.
    expect(PAGES.some((p) => p.id === INVITE.id)).toBe(false)
    expect(NAV.some((p) => p.id === INVITE.id)).toBe(false)
  })

  it('is filtered out of the sitemap, which does not read PAGES', () => {
    // @astrojs/sitemap walks the pages Astro *emitted*, so staying out of the
    // registry does not keep it out of the XML — `/i/` shipped in the sitemap
    // the first time this page was built. Asking Google to crawl a URL that then
    // answers noindex is the contradiction the filter removes.
    const filter = /filter:\s*\(page\)\s*=>\s*(.+?),\n/.exec(astroConfig.replace(/\r/g, ''))?.[1]
    expect(filter, 'no sitemap filter in astro.config.mjs').toBeTruthy()
    // The config's own predicate, run rather than restated: a copy of it here
    // would keep passing after the real one was changed.
    const keeps = new Function('page', `return ${filter}`) as (p: string) => boolean
    expect(keeps('https://ohloco.com/i/')).toBe(false)
    expect(keeps('https://ohloco.com/')).toBe(true)
    expect(keeps('https://ohloco.com/fr/jouer-entre-amis/')).toBe(true)
  })

  it('says it is an invitation, in both languages', () => {
    for (const lang of LANGS) {
      // The unfurled card is a title, a line and a picture. A title written for
      // a search result is far too long for the first of those.
      expect(INVITE.ogTitle?.[lang].length, `ogTitle/${lang}`).toBeLessThanOrEqual(45)
      expect(INVITE.title[lang].length, `title/${lang}`).toBeLessThanOrEqual(60)
      expect(INVITE.description[lang].length, `description/${lang}`).toBeGreaterThanOrEqual(100)
      expect(INVITE.description[lang].length, `description/${lang}`).toBeLessThanOrEqual(155)
    }
  })
})

describe('the art an invitation unfurls into', () => {
  it('is its own image, not the site’s', () => {
    for (const lang of LANGS) {
      expect(INVITE_OG.path[lang]).not.toBe(OG_IMAGE.path[lang])
    }
    expect(INVITE.ogImage).toBe(INVITE_OG)
  })

  it('ships, because a preview that 404s is worse than no preview', () => {
    // CI has no browser: these are generated by `make og` and committed, like
    // the site's own two.
    for (const lang of LANGS) {
      const file = INVITE_OG.path[lang].split('?')[0]
      expect(existsSync(path.join(CLIENT, 'public', file)), file).toBe(true)
    }
  })

  it('draws the same sentence the meta tag carries', () => {
    // One sentence read twice. A literal in the card would drift from the tag
    // beside it the first time either is reworded, and nothing renders the two
    // together for anybody to notice.
    const card = read('src', 'dev', 'OgCard.svelte')
    expect(card).toContain('INVITE.ogTitle')
  })

  it('is reviewable, like every other visual state', () => {
    expect(read('src', 'dev', 'scenes.ts')).toContain("id: 'og-invite'")
  })
})

describe('the URL an invitation is', () => {
  it('is the page itself, so every environment serves it with no help', () => {
    // The whole reason the code rides on a query rather than in the path. A
    // link nobody can open under `astro dev` is a link the E2E suite cannot
    // exercise and a developer cannot try, and it would have looked fine here.
    const url = new URL(tableInviteUrl('ABC234', 'https://loco.test'))
    expect(url.pathname).toBe(INVITE.path.en)
    expect(url.searchParams.get('t')).toBe('ABC234')
  })

  it('needs no fallback in nginx, and must not grow one', () => {
    // The site answers an unknown URL with a real 404 rather than with the app,
    // and that is worth more than the three characters a path form would save.
    expect(nginx).not.toMatch(/location\s+\/i\//)
    expect(nginx).toMatch(/location\s+\/\s*\{[^}]*try_files\s+\$uri\s+\$uri\/\s+=404/)
    expect(astroConfig).not.toMatch(/configureServer|configurePreviewServer/)
  })
})
