import { GameState } from './types'

/** A tab that has just booted: no table, no seat, nothing dealt. */
export const initialState: GameState = {
  screen: 'lobby',
  roomCode: '',
  myIndex: -1,
  sessionToken: '',
  myNickname: '',
  restoreTarget: null,
  errorMsg: '',
  isReconnecting: false,
  serverUpdating: false,

  myHand: [],
  players: [],
  discard: null,
  activeColor: 'red',
  currentTurn: 0,
  direction: 1,
  pendingDraw: 0,
  hasDrawn: false,
  turnDeadline: null,
  mapId: '',
  mapLoading: null,
  swapNotice: null,
  lastPlay: null,
  interruptFlash: null,
  latencies: [],

  unoDeclared: false,
  unoDeclaredByIndex: -1,
  declaredSeats: [],
  myDeclared: false,
  catchWindows: [],
  catchTarget: null,
  unoTimerEnd: null,
  catchFailed: null,
  catchFlash: null,
  catchSpent: false,

  matchFormat: 'BO1',
  maxPlayers: 10,
  roundNumber: 1,
  scoreboard: [],
  roundWinner: '',
  matchWinner: '',
  matchOver: false,
  roundHistory: [],
  matchHistory: [],
  showRoundSummary: false,
  roundNumber_completed: 0,
  roundScores: [],
  pendingGameState: null,
  pendingMatchEnd: null,
  rematchOffers: [],
  rematchNeeded: 0,
  emotes: [],

  searchStartedAt: null,
  matchFound: null,
  isMatchmade: false,
  isSolo: false,
  forfeitBy: null,
  opponentAway: null,
  goneSeats: [],
  departureNotice: null,
}
